/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Tpos_aliases.h"
#include "Tpos.h"
#include "LCD1_aliases.h"
#include "LCD1.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Timer.h"
#include "Reloj.h"
#include "SW_aliases.h"
#include "SW.h"
#include "Thermocouple_1.h"
#include "Tneg_aliases.h"
#include "Tneg.h"
#include "UART_2.h"
#include "RX2.h"
#include "SSR_aliases.h"
#include "SSR.h"
#include "EEPROM.h"
#include "UART_1.h"
#include "RX1.h"
#include "DOOR_aliases.h"
#include "DOOR.h"
#include "LCD2_aliases.h"
#include "LCD2.h"
#include "ADC.h"
#include "ADC_SAR.h"
#include "LM35_aliases.h"
#include "LM35.h"
#include "VENT1_aliases.h"
#include "VENT1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "Timer2.h"
#include "leeT.h"
#include "UART_3.h"
#include "UART_2_IntClock.h"
#include "UART_1_IntClock.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_SAR_IRQ.h"
#include "ADC_SAR_theACLK.h"
#include "I2C_IntClock.h"
#include "UART_3_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

